spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/demo?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password
    pool:
      initial-size: 10
      max-size: 100
      max-idle-time: 30m
      validation-query: SHOW DATABASES

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  port: 9000